### ISSUE TITLE
hi everyone,  

### ISSUE THREAD

**Issue by claus25** [claus25/ffcu#1]
hi everyone 
I'm actually working on rgbd semantic segmentation , when I trying to modify and  run train.py code then I have this error message

 'pwd' is not recognized as an internal or external command,
operable program or batch file.
22 20:01:45 PyTorch Version 1.9.1+cpu, Furnace Version 0.1.1
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/RGBD_Semantic_Segmentation_PyTorch-master/model/SA-Gate.nyu.432/train.py", line 35, in <module>
    with Engine(custom_parser=parser) as engine:
  File "C:\Users\lenovo\Desktop\RGBD_Semantic_Segmentation_PyTorch-master\furnace\engine\engine.py", line 71, in __init__
    self.devices = parse_devices(self.args.devices)
  File "C:\Users\lenovo\Desktop\RGBD_Semantic_Segmentation_PyTorch-master\furnace\utils\pyt_utils.py", line 229, in parse_devices
    device = int(d)
ValueError: invalid literal for int() with base 10: ''

I don't know why

**Comment by claus25** [comment]
the train code is from model/SA-Gate.nyu.432 but I only have one GPU

**Comment by claus25** [comment]
please someone help me

**Comment by claus25** [comment]
please someone help me
